pipeline {
    agent any
    
    parameters {
        // GitHub  사용자명 입력
        string(name: 'GITHUB_USERNAME',  defaultValue: '2025-07-JAVA-DEVELOPER-162', description: 'GitHub  사용자명을 입력하세요.')
    }			
    environment {
        GITHUB_SCRIPT_URL = "https://github.com/${GITHUB_USERNAME}/kubernetes-guest-script.git"
        //deployment.yaml -> image: academyitwill/guest:v1
         //실습 step 번호 - (수정x)
         STEP_NUM = 'step23'
    }

    stages {
        stage('릴리즈파일 체크아웃') {
            steps {
                checkout scmGit(branches: [[name: '*/main']],
                        extensions: [[$class: 'SparseCheckoutPaths',
                                      sparseCheckoutPaths: [[path: "/${STEP_NUM}"]]]],
                        userRemoteConfigs: [[url: "${GITHUB_SCRIPT_URL}"]])
            }
        }

        stage('쿠버네티스 Blue배포') {
            steps {
                sh "kubectl apply -f ./${STEP_NUM}/deploy/k8s/blue/namespace.yaml"
                sh "kubectl apply -f ./${STEP_NUM}/deploy/k8s/blue/service.yaml"
                sh "kubectl apply -f ./${STEP_NUM}/deploy/k8s/blue/deployment.yaml"
            }
        }

        stage('배포 시작') {
            steps {
                input message: '수동배포 시작', ok: "Yes"
            }
        }

        stage('쿠버네티스 Green배포') {
            steps {
	            sh "kubectl apply -f ./${STEP_NUM}/deploy/k8s/green/deployment.yaml"
                sh "kubectl apply -f ./${STEP_NUM}/deploy/k8s/green/service.yaml"
            }
        }

        stage('전환여부 확인') {
            steps {
                script {
                    returnValue = input message: 'Green 전환?', ok: "Yes", parameters: [booleanParam(defaultValue: true, name: 'IS_SWITCHED')]
                    if (returnValue) {
                        sh "kubectl patch -n guest-namespace-step23 svc guest-service -p '{\"spec\": {\"selector\": {\"blue-green-no\": \"2\"}}}'"
                    }
                }
            }
        }

        stage('롤백 확인') {
            steps {
                script {
                    returnValue = input message: 'Blue 롤백?', parameters: [choice(choices: ['done', 'rollback'], name: 'IS_ROLLBACk')]
                    if (returnValue == "done") {
                        sh "kubectl delete -f ./${STEP_NUM}/deploy/k8s/blue/deployment.yaml"
                        sh "kubectl delete -f ./${STEP_NUM}/deploy/k8s/green/service.yaml"
                        sh "kubectl patch -n guest-namespace-step2 svc guest-service -p '{\"metadata\": {\"labels\": {\"version\": \"2.0.0\"}}}'"
                    }
                    if (returnValue == "rollback") {
                        sh "kubectl patch -n guest-namespace-step23 svc guest-service -p '{\"spec\": {\"selector\": {\"blue-green-no\": \"1\"}}}'"
                    }
                }
            }
        }
    }

}
